import { Creator, Drop } from "./types";

export const DEFAULT_CREATORS: Creator[] = [
  {
    id: "mrbeast",
    name: "MrBeast (Jimmy)",
    handle: "@mrbeast",
    avatarUrl: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80",
    category: "Financial / Entrepreneurship",
    followersCount: "490M",
    voiceName: "Fenrir",
    description: "Philanthropist, content pioneer, and founder of Beast Financial tools. Pushing direct memberships that transcend generic subscription limitations.",
    videoChannelContext: "MrBeast Financial / Step App Campaign"
  },
  {
    id: "garyv",
    name: "Gary Vaynerchuk",
    handle: "@garyvee",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    category: "Business & Productivity",
    followersCount: "10.4M",
    voiceName: "Zephyr",
    description: "CEO of VaynerMedia, investor, & original social media advocate. Focused on direct message channels that bypass algorithmic suppression.",
    videoChannelContext: "VaynerMedia Keynotes"
  },
  {
    id: "charlemagne",
    name: "Charlemagne tha God",
    handle: "@cthagod",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    category: "Comedy & Commentary",
    followersCount: "4.2M",
    voiceName: "Charon",
    description: "Co-host of The Breakfast Club, media mogul, and cultural commentator. Creator of the famous 'Donkey of the Day' segment.",
    videoChannelContext: "The Breakfast Club Show"
  },
  {
    id: "eyl",
    name: "Earn Your Leisure",
    handle: "@earnyourleisure",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    category: "Financial Literacy / Invest Fest",
    followersCount: "1.8M",
    voiceName: "Kore",
    description: "Rashad Bilal & Troy Millings breaking down business models, investment protocols, and hosting 'Invest Fest' annually in Atlanta.",
    videoChannelContext: "EYL Podcast & Invest Fest Highlights"
  },
  {
    id: "sohk",
    name: "School of Hard Knocks (James)",
    handle: "@sohk_james",
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    category: "Inspirational / Wisdom",
    followersCount: "2.4M",
    voiceName: "Puck",
    description: "James interviewing self-made millionaires, billionaires, and industry leaders on the streets of New York, capturing actionable wisdom.",
    videoChannelContext: "SOHK Millionaire Series"
  },
  {
    id: "santa",
    name: "Santa Claus (Magical)",
    handle: "@santa_official",
    avatarUrl: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=150&auto=format&fit=crop&q=80",
    category: "Family & Kids (Seasonal)",
    followersCount: "Family Only",
    voiceName: "Zephyr",
    description: "Durable, heartwarming, and parent-triggered family messages delivered directly from the North Pole on custom calendar triggers.",
    videoChannelContext: "North Pole Toy Workshop Live Stream"
  },
  {
    id: "horoscope",
    name: "Cosmic Daily Horoscope",
    handle: "@cosmic_insights",
    avatarUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=150&auto=format&fit=crop&q=80",
    category: "Spiritual & Lifestyle",
    followersCount: "12M Delivery",
    voiceName: "Kore",
    description: "Personalized, segmented astrological updates broken into romance, career, and daily Luck indicators without generic feed clutter.",
    videoChannelContext: "Celestial Planetary Alignment Ticker"
  },
  {
    id: "naughtysanta",
    name: "Naughty Santa (Adult Parody)",
    handle: "@naughty_santa",
    avatarUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=150&auto=format&fit=crop&q=80",
    category: "Humor & Comedy (Adult)",
    followersCount: "18+ Rated",
    voiceName: "Puck",
    description: "A cheeky, tongue-in-cheek holiday parody series for mature audiences. Strict opt-in filter required to access.",
    videoChannelContext: "Late Night Christmas Comedy Vault"
  }
];

export const DEFAULT_DROPS: Drop[] = [
  {
    id: "drop-mrbeast-membership",
    creatorId: "mrbeast",
    title: "The Death of Static Following",
    content: "If you are focusing solely on a 'follower count' metric, you are already five years too late. Having 400 million followers means nothing if an algorithm decides who gets to see your content. That's why I bought Step App, and why I file trademarks for MrBeast Financial. You need to build a direct, sovereign membership where when you click 'Send', every single phone vibrates instantly. That direct, non-interrupted pipeline is the real moat of our generation.",
    voiceName: "Fenrir",
    category: "Financial / Entrepreneurship",
    dateSent: "2026-06-10",
    tone: "Inspirational",
    isAdult: false,
    anchorTitle: "The Step App Acquisition & Member Blueprint",
    anchorSource: "YouTube",
    anchorLink: "https://youtube.com/watch?v=BeastFinStep",
    anchorTimeCode: "12:45",
    transcriptContext: "The future is sovereign creator channels. The traditional web-app subscriptions are broken. We are launching Beast Financial to give users direct financial incentives and true delivery assurance."
  },
  {
    id: "drop-charlemagne-donkey",
    creatorId: "charlemagne",
    title: "Donkey of the Day: The Directional Excuse",
    content: "Florida man drives 90 miles an hour down the wrong side of the Turnpike. Cop pulls him over, and this absolute intellectual genius actually tells the officer: 'Officer, the direction I am traveling in has no meaning. The only thing with meaning is that I reach my destination.' Now, I respect the philosophical effort, my brother, but you put everybody on that highway at risk! For attempting to debate your way out of a standard traffic violation with quantum physics, you are receiving today's official Donkey of the Day! Don't let your self-declared meaning land you in a county cell.",
    voiceName: "Charon",
    category: "Comedy & Commentary",
    dateSent: "2026-06-10",
    tone: "Humor/Opinion",
    isAdult: false,
    anchorTitle: "Florida Turnpike Incident Special Commentary",
    anchorSource: "Radio",
    anchorLink: "https://thebreakfastclub.iheart.com/shows",
    anchorTimeCode: "01:22:40",
    transcriptContext: "This driver actually tried to give a discourse on directional vectors. That is a wild excuse for nearly causing a head-on collision."
  },
  {
    id: "drop-garyv-bypass",
    creatorId: "garyv",
    title: "The Zero-Surveillance Ad Revolution",
    content: "Listen to me! The marketing world is going to have its head absolutely blown off. Privacy guidelines are tightening, data cookies are dying, and platforms are charging you ridiculous CPMs just to guess what a user wants based on surveillance. If a customer explicitly tells the app 'I want fitness tips and financial news,' you show them a fitness ad! There's no tracking needed, and no creepiness. That commands three times the CPM because it's deterministic. Stop guessing and let people declare what they want to see!",
    voiceName: "Zephyr",
    category: "Business & Productivity",
    dateSent: "2026-06-09",
    tone: "Educational",
    isAdult: false,
    anchorTitle: "Live Keynote on Zero-Tracking Ad Architecture",
    anchorSource: "Podcast",
    anchorLink: "https://garyvaynerchuk.com/audio-experience",
    anchorTimeCode: "45:10",
    transcriptContext: "User-declared interest targeting is the only form of digital marketing that preserves user trust while delivering immediate premium engagement..."
  },
  {
    id: "drop-eyl-assets",
    creatorId: "eyl",
    title: "Assets Over Liabilities Explained",
    content: "At Invest Fest, we talk to so many young entrepreneurs who make their first fifty thousand and buy a lease on a sports car. That is a liability. You must redirect those initial wins into cash-flowing assets that sustain your lifestyle before you accumulate depreciation. Buy commercial real estate, invest in indexed protocols, or build out private intellectual infrastructure first. Let your assets pay for your luxury, never your active labor.",
    voiceName: "Kore",
    category: "Financial Literacy / Invest Fest",
    dateSent: "2026-06-08",
    tone: "Educational",
    isAdult: false,
    anchorTitle: "EYL Episode 340: The Compound Effect Strategy",
    anchorSource: "Podcast",
    anchorLink: "https://earnyourleisure.com/podcasts",
    anchorTimeCode: "22:15",
    transcriptContext: "When we analyze compound wealth drivers, the initial capital allocation determines whether a business stays liquid through interest rate adjustments..."
  },
  {
    id: "drop-sohk-billionaire",
    creatorId: "sohk",
    title: "Wisdom from NYC's Hardest Knocks",
    content: "I met an 82-year-old self-made real estate billionaire on Park Avenue yesterday. I asked him, 'What is the biggest regret you see young people make today?' He looked me in the eyes and said: 'They are looking for micro-shortcuts before they build macro-competence. They spend all day reading about morning routines instead of picking up the phone and calling fifty prospective clients.' Real competence is earned in the arena of active labor, not in the stands of intellectual preparation.",
    voiceName: "Puck",
    category: "Inspirational / Wisdom",
    dateSent: "2026-06-07",
    tone: "Inspirational",
    isAdult: false,
    anchorTitle: "Wisdom from Park Ave Billionaire Interview",
    anchorSource: "YouTube",
    anchorLink: "https://youtube.com/watch?v=SOHKNYCJames",
    anchorTimeCode: "04:32",
    transcriptContext: "Action is the ultimate filter. Competence isn't structured until you handle real customer rejections on consecutive phone campaigns."
  },
  {
    id: "drop-santa-greetings",
    creatorId: "santa",
    title: "A Jolly Morning at the Workshop!",
    content: "Ho Ho Ho! A very cheerful greetings to you! The elves are working in triple-overtime here at the North Pole toy workshop, and I wanted to send you a quick smile today. Remember, being helpful around the house and showing kindness to your siblings is the finest gift you can ever make. I am keeping my list tidy, and I can't wait to check in on you again soon! Have a wonderfully magical and jolly day!",
    voiceName: "Zephyr",
    category: "Family & Kids (Seasonal)",
    dateSent: "2026-06-06",
    tone: "Seasonal",
    isAdult: false,
    anchorTitle: "North Pole Toy Workshop Festive Update",
    anchorSource: "Broadcast",
    anchorLink: "https://santa.northpole/radio",
    anchorTimeCode: "02:15",
    transcriptContext: "The magical toy workshop is operating at maximum capacity. This seasonal drop target is verified by parent-enabled quiet hour constraints."
  },
  {
    id: "drop-horoscope-gemini",
    creatorId: "horoscope",
    title: "Gemini: Embrace Strategic Quietness",
    content: "Romance: 85% | Lucky Hours: 3 PM - 5 PM. Mercury aligns with Pluto tonight, urging you to keep your next major career move close to your chest. A sudden urge to over-explain a pre-launch plan will arise this afternoon—resist it. The true cosmic advantage belongs to those who build in absolute silent alignment, revealing their progress only when the structure is solid. Trust your inner guide and ignore the noise of outside opinions.",
    voiceName: "Kore",
    category: "Spiritual & Lifestyle",
    dateSent: "2026-06-10",
    tone: "Devotional",
    isAdult: false,
    anchorTitle: "Mercury-Pluto Sextile Astrological Ephemeris",
    anchorSource: "Website",
    anchorLink: "https://cosmic-horoscopes.com/gemini",
    anchorTimeCode: "00:00",
    transcriptContext: "Planetary vectors support strategic containment today. Focus romance energy in the late afternoon and avoid premature social announcements."
  },
  {
    id: "drop-parody-christmas",
    creatorId: "naughtysanta",
    title: "Santa: The Reindeer Union's Demands",
    content: "Alright, look—I'm about two seconds away from firing Rudolph. This guy has one shiny nose and now he's demanding premium organic moss and dental insurance for all nine reindeer! They're threatening to strike on December 15th unless I give them a heated barn. That is outrageous! I'm the one carrying a 4-ton bag down physical chimneys, and they're complaining about some cold wind? If you hear footsteps on your roof early, it might be me hiring some temporary Uber-Reindeer. Let's keep this between us!",
    voiceName: "Puck",
    category: "Humor & Comedy (Adult)",
    dateSent: "2026-06-10",
    tone: "Humor/Opinion",
    isAdult: true,
    anchorTitle: "Classic Christmas Parody Comedy Archive #3",
    anchorSource: "Broadcast",
    anchorLink: "https://comedyvault.com/mature-santa-strikes",
    anchorTimeCode: "18:40",
    transcriptContext: "A humorous adult-themed parody discussing reindeer negotiations and corporate toy scheduling at the North Pole."
  },
  {
    id: "drop-mrbeast-hyper",
    creatorId: "mrbeast",
    title: "The $1,000,000 Direct Message Challenge",
    content: "We literally just gave away one million dollars to a subscriber who replied to our direct notification with the word 'ASSET' in under the first three seconds flat! Try doing that on standard social platforms where notifications get delayed or completely blocked by corporate filtering algorithms. If you own your audience directly, you have the superpower to command instant attention. Move your followers to direct channels, keep building real pipelines, and dominate your niche!",
    voiceName: "Fenrir",
    category: "Financial / Entrepreneurship",
    dateSent: "2026-06-11",
    tone: "Inspirational",
    isAdult: false,
    anchorTitle: "Ultimate Notification Challenge Winner Reveal",
    anchorSource: "YouTube",
    anchorLink: "https://youtube.com/watch?v=BeastFinStepMillion",
    anchorTimeCode: "05:12",
    transcriptContext: "The notification went live and reached 25 million devices within 1.2 seconds. This demonstrates the immense potential of sovereign micro-channels over traditional distribution models."
  },
  {
    id: "drop-charlemagne-wake",
    creatorId: "charlemagne",
    title: "Donkey of the Day: The Micro-Shortcut Delusion",
    content: "If you think buying mock followers and posting artificial, AI-generated generic templates is going to make you an overnight authority, please wake up and join reality. You can't skip the active labor. True cultural competence is built on New York concrete, handling rejections, and talking directly to the community. You are earning today's Donkey of the Day for refusing to put in the actual work while expecting premium enterprise returns.",
    voiceName: "Charon",
    category: "Comedy & Commentary",
    dateSent: "2026-06-11",
    tone: "Humor/Opinion",
    isAdult: false,
    anchorTitle: "The Breakfast Club: Cultural Autonomy Commentary",
    anchorSource: "Radio",
    anchorLink: "https://thebreakfastclub.iheart.com/shows",
    anchorTimeCode: "01:05:10",
    transcriptContext: "We have to remind our audience that shortcut-seeking behavior is the easiest way to lose your momentum in this highly competitive industry."
  },
  {
    id: "drop-garyv-tiktok",
    creatorId: "garyv",
    title: "The Attention Arbitrage Landscape",
    content: "Listen to me! Stop crying about the TikTok changes or the Instagram algorithm decline! The only thing that has premium value in 2026 is attention, period. When attention moves, you move your distribution strategy. Stop getting emotionally attached to a single medium or an old playbook. Direct messaging, SMS, and user-declared databases are your absolute insurance policy against platform decay. Control your connection!",
    voiceName: "Zephyr",
    category: "Business & Productivity",
    dateSent: "2026-06-11",
    tone: "Educational",
    isAdult: false,
    anchorTitle: "VaynerMedia Private Keynote on Distribution Arbitrage",
    anchorSource: "Podcast",
    anchorLink: "https://garyvaynerchuk.com/audio-experience",
    anchorTimeCode: "18:22",
    transcriptContext: "Attention is highly liquid. We must ensure our client brands are diversified away from single centralized platform hazards."
  },
  {
    id: "drop-eyl-generational",
    creatorId: "eyl",
    title: "Constructing Generational Wealth Vaults",
    content: "When you analyze the long-term wealth of families like the Rockefellers, they don't depend on singular active salaries. They set up family trusts, accumulate real estate portfolios, and establish private cash-flow channels. If you are a creator and you rely entirely on an external platform's ad-network split, you are one policy change away from bankruptcy. Establish direct premium membership systems to build a generational fortress.",
    voiceName: "Kore",
    category: "Financial Literacy / Invest Fest",
    dateSent: "2026-06-11",
    tone: "Educational",
    isAdult: false,
    anchorTitle: "EYL Invest Fest Masterclass: Generational Sovereignty",
    anchorSource: "Podcast",
    anchorLink: "https://earnyourleisure.com/podcasts",
    anchorTimeCode: "1:44:00",
    transcriptContext: "Trust structuring and subscription equity are the twin engines of modern financial independence for cultural creators."
  },
  {
    id: "drop-sohk-billionaire2",
    creatorId: "sohk",
    title: "Street Level Execution Beats Classrooms",
    content: "I met a 44-year-old self-made logistics billionaire in SoHo. I asked him, 'What is the biggest myth people learn in business school?' He laughed and said: 'They teach you to write 50-page market analyses. In the real world, you launch a crude version in 3 days, call 100 people, watch it fail, and adapt instantly. Execution in the face of uncertainty beats abstract theory every single time.' Stop planning and start active testing today.",
    voiceName: "Puck",
    category: "Inspirational / Wisdom",
    dateSent: "2026-06-11",
    tone: "Inspirational",
    isAdult: false,
    anchorTitle: "SOHK SoHo Millionaire Series: Fast Prototyping",
    anchorSource: "YouTube",
    anchorLink: "https://youtube.com/watch?v=SOHKNYCJamesSoho",
    anchorTimeCode: "08:15",
    transcriptContext: "The market is a dynamic feedback system. Static planning is a comfort mechanism that shields you from real competitive signals."
  },
  {
    id: "drop-horoscope-scorpio",
    creatorId: "horoscope",
    title: "Scorpio: Channel the Silent Forge",
    content: "Romance: 92% | Lucky Hours: 9 PM - Midnight. Pluto retrogrades into your solar house of communication, signalling a deep internal restructuring. You are urged to break free from the performance trap of social validation feeds. Channel your intense emotional power into the silent forge. Build your passion projects in secret. Your direct soul connections require zero administrative approvals—reclaim your sovereign authority now.",
    voiceName: "Kore",
    category: "Spiritual & Lifestyle",
    dateSent: "2026-06-11",
    tone: "Devotional",
    isAdult: false,
    anchorTitle: "Pluto Retrograde Solar Communication Coordinates",
    anchorSource: "Website",
    anchorLink: "https://cosmic-horoscopes.com/scorpio",
    anchorTimeCode: "00:00",
    transcriptContext: "Cosmic alignments favor deep creative secrecy. Late evening supports romantic renewals in absolute distraction-free surroundings."
  },
  {
    id: "drop-santa-elfstrike",
    creatorId: "santa",
    title: "The Cocoa Break Dispute",
    content: "Ho Ho Ho! A quick update on the Arctic kitchen situation. The baking elves requested an extension to their scheduled hot-cocoa breaks to thirty minutes! I told them that if active candy canes are not decorated at forty units per minute, the production timeline drops below threshold. We compromised by adding mini marshmallows to their standard beverage rations. Harmony is restored! Remember, look for peaceful compromises in all daily challenges!",
    voiceName: "Zephyr",
    category: "Family & Kids (Seasonal)",
    dateSent: "2026-06-11",
    tone: "Seasonal",
    isAdult: false,
    anchorTitle: "North Pole Cafeteria Settlement Records",
    anchorSource: "Broadcast",
    anchorLink: "https://santa.northpole/radio",
    anchorTimeCode: "06:12",
    transcriptContext: "Elf labor negotiations concluded positively. Marshmallow allocations adjusted according to daily toy outputs."
  },
  {
    id: "drop-parody-reindeer",
    creatorId: "naughtysanta",
    title: "Rudolph's Red Nose Demands",
    content: "Alright, folks, Rudolph is at it again. This red-nosed diva wants his own personal dressing room with heated lighting and gourmet carrots. He claims his nose is 'an irreplaceable navigation instrument.' I told him navigation instruments don't demand full dental coverage for their entire extended family. If he keeps this attitude up, I'm packing his bags and putting an old lighthouse lamp on the front of the sleigh on Christmas Eve. Let's see how much leverage he has then!",
    voiceName: "Puck",
    category: "Humor & Comedy (Adult)",
    dateSent: "2026-06-11",
    tone: "Humor/Opinion",
    isAdult: true,
    anchorTitle: "Classic Christmas Parody Comedy Archive #4",
    anchorSource: "Broadcast",
    anchorLink: "https://comedyvault.com/mature-santa-strikes",
    anchorTimeCode: "22:15",
    transcriptContext: "A humorous adult-themed parody of reindeer billing rates and sleigh instrumentation costs."
  },
  {
    id: "drop-eyl-collateral",
    creatorId: "eyl",
    title: "Intellectual Property as Equity",
    content: "In the modern economy, your absolute highest wealth multiplier is intellectual property. Think about it: when you build a brand or a software tool, you can license it, sell it, or borrow against it as real collateral. Most people carry around priceless knowledge in their heads but never structure it into a registered asset. Do not let your ideas expire on rented platforms. Formalize your copyright, register your trademarks, and convert active know-how into permanent paper equity.",
    voiceName: "Kore",
    category: "Financial Literacy / Invest Fest",
    dateSent: "2026-06-09",
    tone: "Educational",
    isAdult: false,
    anchorTitle: "EYL Special Masterclass: Trademark Structuring",
    anchorSource: "Podcast",
    anchorLink: "https://earnyourleisure.com/podcasts",
    anchorTimeCode: "55:30",
    transcriptContext: "IP capitalization remains the least understood mechanism of modern wealth acquisition for self-directed media businesses."
  },
  {
    id: "drop-horoscope-leo",
    creatorId: "horoscope",
    title: "Leo: Reclaim Your Solar Shield",
    content: "Romance: 95% | Lucky Hours: 8 AM - 11 AM. The Sun enters your career sector tomorrow morning, amplifying your natural magnetic authority. If you have been hiding behind other people's templates, this is your stellar mandate to step into the light. Protect your creative force with a solar shield—do not let critics or generic platform noise dilute your voice. A romance encounter under the Leo moon brings absolute deep clarity.",
    voiceName: "Kore",
    category: "Spiritual & Lifestyle",
    dateSent: "2026-06-11",
    tone: "Devotional",
    isAdult: false,
    anchorTitle: "Solar Ingress into Career Coordinates",
    anchorSource: "Website",
    anchorLink: "https://cosmic-horoscopes.com/leo",
    anchorTimeCode: "00:00",
    transcriptContext: "An intensive boost in creative confidence is astronomically favored today. Romances started under Leo moon show exceptional durability."
  },
  {
    id: "drop-sohk-adversity",
    creatorId: "sohk",
    title: "The Comfort Trap Danger",
    content: "I interviewed a 52-year-old self-made software billionaire in Tribeca. I asked him, 'What is the absolute fastest way for an ambitious founder to kill their momentum?' He smiled and said: 'Comfort. The minute you rent the nice office, buy the fancy chairs, and hire administrators to do your calling, you stop tasting the dirt. You lose the hunting instinct.' Rejection is the blood that feeds the muscle. Keep yourself physically in the line of fire.",
    voiceName: "Puck",
    category: "Inspirational / Wisdom",
    dateSent: "2026-06-11",
    tone: "Inspirational",
    isAdult: false,
    anchorTitle: "SOHK Tribeca Tech Founders Series",
    anchorSource: "YouTube",
    anchorLink: "https://youtube.com/watch?v=SOHKNYCJamesTribeca",
    anchorTimeCode: "12:05",
    transcriptContext: "Staying hyper-lean prevents administrative bloat and keeps the core execution loops highly responsive."
  }
];

